### PR TITLE
Update tftpd.lua

### PR DESCRIPTION
**Pull request by devyte**
Added RRQ, timeout, error replies
Improved error handling

### CODE REVIEW

**Comment by devyte** [comment]
Thanks for the initial implementation. I was looking for an tftp server for the nodemcu, and yours was a very good start!
I think I've completed the implementation, although the whole TID thing is not implemented.
Anyways, try it out and merge if you like!

**Comment by devyte** [comment]
oh, usage is like this:
dofile("tftpd.lc")()
or
dofile("tftpd.lua")()
in case it's not compiled.

**Comment by renevdzee** [comment]
Thanks devyte, much better than what I had so far! I will definitely merge this one. 
Only one issue (I think). When sending a file (RRQ) the _tblk should only be incremented if a ACK is received. On timeout the block should be resend. Do you agree? 

BTW, could you explain why you changed it to a function? I was thinking into using modifying it into require("tftpd") module (tries .lc and .lua in that order), however I don't know how to do that yet.

**Comment by renevdzee** [comment]
created a branch "resend" with some untested code for resending data blocks on timeout,
https://github.com/renevdzee/nodemcu_tftpd/tree/resend

**Comment by devyte** [comment]
You're correct, I did not really pay attention to what should happen when an ACK is not received before a timeout. Then again, I don't really have a proper way of testing such a case, unless I make my own tftp client as well...
I made it into a function based on the ideas I found while looking at the http server by Marcos Kirsch:
https://github.com/marcoskirsch/nodemcu-httpserver

My thoughts:
The implementation requires a global context  (e.g.: _tblk) . As a function, the global vars can be declared local, and therefore the context is kept inside of the function instead of polluting the global namespace.
When the returned socket is closed, the onReceive function is released, which in turn released the context as well, so you get a full cleanup when garbage is collected.
You could, in theory, run two tftp servers on different ports, because each call to the function has its own isolated context, and so they don't interfere. I learned this the hard way while trying to refactor Marcos's code.

I'm not a lua expert (I started learning only a week ago), but my understanding is that making it a function allows automatic releasing of resources, but use of packages and require loads on demand, and then doesn't unload again, unless you explicitly do some things. I could be wrong, of course...

**Pull request merged**
